/**
 * It translates a text to other language
 */
function translate(text, language){
	switch(language){
		case 'es':
			return es[text];
			break;
		case 'ga':
			return ga[text];
			break;
		case 'en':
			return en[text];
			break;
		default:
			return en[text];
			break;
	}
}

/**
 * Spanish dictionary
 */
var es = {
	'World' : 'Mundo',
	'Elements' : 'Elementos',
	'Restrictions' : 'Restricciones',
	'Period' : 'Ciclos',
	'Actions' : 'Acciones',
	'Ranges' : 'Rangos',
	'Behaviour' : 'Comportamiento',
	'Total period - Wrong format' : 'Duración total - Formato incorrecto',
	'Total period - It must be equal or more than 2' : 'Duración total - Tiene que ser igual o mayor que 2',
	'Daylight period - Wrong format' : 'Duración del día - Formato incorrecto',
	'Daylight period - It must be equal or more than 1' : 'Duración del día - Tiene que ser igual o mayor que 1',
	'Night period - Wrong format' : 'Duración de la noche - Formato incorrecto',
	'Night period - It must be equal or more than 1' : 'Duración de la noche - Tiene que ser igual o mayor que 1',
	'Size (height) of the world - Wrong format' : 'Dimensión (largo) del mundo - Formato incorrecto',
	'Size (height) of the world - It must be equal or more than 1' : 'Dimensión (largo) del mundo - Tiene que ser igual o mayor que 1',
	'Size (width) of the world - Wrong format' : 'Dimensión (ancho) del mundo - Formato incorrecto',
	'Size (width) of the world - It must be equal or more than 1' : 'Dimensión (ancho) del mundo - Tiene que ser igual o mayor que 1',
	'Change weather each (cycles) - Wrong format' : 'Cambiar tiempo cada (ciclos) - Formato incorrecto',
	'Change weather each (cycles) - It must be equal or less than total period' : 'Cambiar tiempo cada (ciclos) - Tiene que ser igual o menor que el número de ciclos de ejecución',
	'Amount of carrots - Wrong format' : 'Cantidad de comida para presas - Formato incorrecto',
	'Amount of trees - Wrong format' : 'Cantidad de elementos estáticos - Formato incorrecto',
	'Amount of lair - Wrong format' : 'Cantidad de elementos de ocultación - Formato incorrecto',
	'Amount of rabbits - Wrong format' : 'Cantidad de presas - Formato incorrecto',
	'Amount of wolves - Wrong format' : 'Cantidad de depredadores - Formato incorrecto',
	'Begining amount of elements - It must be equal or less than size world' : 'Cantidad inicial de elementos - Tiene que ser menor o igual que la dimensión del mundo',
	'Regeneration of carrots each - Wrong format' : 'Regeneración de comida para presas cada - Formato incorrecto',
	'Regeneration of carrots each - The number of cycles mustn\'t be more than total period' : 'Regenara comida para presas cada - El número de ciclos no puede ser mayor que el número de ciclos de ejecución',
	'Regeneration of carrots each - The number of cycles must be more than 0' : 'Regenara comida para presas cada - El número de ciclos tiene que ser mayor que 0',
	'Regeneration of carrots (amount) - Wrong format' : 'Regenara comida para presas (cantidad) - Formato incorrecto',
	'Cycles without eat (rabbits) - Wrong format' : 'Ciclos sin comer (presas) - Formato incorrecto',
	'Cycles without eat (wolves) - Wrong format' : 'Ciclos sin comer (depredadores) - Formato incorrecto',
	'Cycles without sleep (rabbits) - Wrong format' : 'Ciclos sin dormir (presas) - Formato incorrecto',
	'Cycles without sleep (wolves) - Wrong format' : 'Ciclos sin dormir (depredadores) - Formato incorrecto',
	'Rabbits - Limit each (cycles) - Wrong format' : 'Presas - Límite cada (ciclos) - Formato incorrecto',
	'Rabbits - Maximum amount - Wrong format' : 'Presas - Cantidad máxima - Formato incorrecto',
	'Wolves - Limit each (cycles) - Wrong format' : 'Depredadores - Límite cada (ciclos) - Formato incorrecto',
	'Wolves - Maximum amount - Wrong format' : 'Depredadores - Cantidad máxima - Formato incorrecto',
	'Rabbits - Need (cycles) - Wrong format' : 'Presas - Necesitan (ciclos) - Formato incorrecto',
	'Rabbits - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Presas - Necesitan (ciclos) - No se puede tardar más de la duración del día en comer',
	'Wolves - Need (cycles) - Wrong format' : 'Depredadores - Necesitan (ciclos) - Formato incorrecto',
	'Wolves - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Depredadores - Necesitan (ciclos) - No se puede tardar más de la duración del día en comer',
	'Rabbits - Are sated for (cycles) - Wrong format' : 'Presas - Están saciados durante (ciclos) - Formato incorrecto',
	'Rabbits - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Presas - Están saciados durante (ciclos) - El número de ciclos tiene que ser menor que el tiempo que pueden pasar sin comer',
	'Wolves - Are sated for (cycles) - Wrong format' : 'Depredadores - Están saciados durante (ciclos) - Formato incorrecto',
	'Wolves - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Depredadores - Están saciados durante (ciclos) - El número de ciclos tiene que ser menor que el tiempo que pueden pasar sin comer',
	'Rabbits - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Presas - Necesitan (ciclos) - Duración incorrecta, no puede ser mayor que +25% de la duración de la noche',
	'Wolves - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Depredadores - Necesitan (ciclos) - Duración incorrecta, no puede ser mayor que +25% de la duración de la noche',
	'Points per actions - Rabbits - Wrong format' : 'Puntos por acciones - Presas - Formato incorrecto',
	'Points per actions - Wolves - Wrong format' : 'Puntos por acciones - Depredadores - Formato incorrecto',
	'Use per action - Smell - Rabbits - Wrong format' : 'Consumo por acción - Olfatear - Presas - Formato incorrecto',
	'Use per action - Smell - Wolves - Wrong format' : 'Consumo por acción - Olfatear - Depredadores - Formato incorrecto',
	'Use per action - Hear - Rabbits - Wrong format' : 'Consumo por acción - Oir - Presas - Formato incorrecto',
	'Use per action - Hear - Wolves - Wrong format' : 'Consumo por acción - Oir - Depredadores - Formato incorrecto',
	'Use per action - See - Rabbits - Wrong format' : 'Consumo por acción - Ver - Depredadores - Formato incorrecto',
	'Use per action - See - Wolves - Wrong format' : 'Consumo por acción - Ver - Depredadores - Formato incorrecto',
	'Use per action - Move - Rabbits - Wrong format' : 'Consumo por acción - Mover - Depredadores - Formato incorrecto',
	'Use per action - Move - Wolves - Wrong format' : 'Consumo por acción - Mover - Depredadores - Formato incorrecto',
	'Use per action - Sleep - Rabbits - Wrong format' : 'Consumo por acción - Dormir - Depredadores - Formato incorrecto',
	'Use per action - Sleep - Wolves - Wrong format' : 'Consumo por acción - Dormir - Depredadores - Formato incorrecto',
	'Use per action - Breed - Rabbits - Wrong format' : 'Consumo por acción - Reproducirse - Depredadores - Formato incorrecto',
	'Use per action - Breed - Wolves - Wrong format' : 'Consumo por acción - Reproducirse - Depredadores - Formato incorrecto',
	'Range per action - See - Rabbits - Wrong format' : 'Rango por acción - Ver - Presas - Formato incorrecto',
	'Range per action - See - Wolves - Wrong format' : 'Rango por acción - Ver - Depredadores - Formato incorrecto',
	'Range per action - Smell - Rabbits - Wrong format' : 'Rango por acción - Olfatear - Presas - Formato incorrecto',
	'Range per action - Smell - Wolves - Wrong format' : 'Rango por acción - Olfatear - Depredadores - Formato incorrecto',
	'Range per action - See - Rabbits - Wrong format' : 'Rango por acción - Ver - Presas - Formato incorrecto',
	'Range per action - See - Wolves - Wrong format' : 'Rango por acción - Ver - Depredadores - Formato incorrecto',
	'Until (cycles) after eating - Rabbits - Wrong format' : 'Hasta (ciclos) después de comer - Presas - Formato incorrecto',
	'Until (cycles) after eating - Wolves - Wrong format' : 'Hasta (ciclos) después de comer - Depredadores - Formato incorrecto',
	'Until (cycles) after sleeping - Rabbits - Wrong format' : 'Hasta (ciclos) después de dormir - Presas - Formato incorrecto',
	'Until (cycles) after sleeping - Wolves - Wrong format' : 'Hasta (ciclos) después de dormir - Depredadores - Formato incorrecto',
	'Weather' : 'Tiempo atmosférico',
	'Cycles' : 'Ciclos',
	'Sunny' : 'Soleado',
	'Rainy' : 'Lluvioso',
	'Windy' : 'Con viento',
	'Foggy' : 'Con niebla',
	'Rabbits' : 'Presas',
	'Wolves' : 'Depredadores',
	'Carrots' : 'Comida para presas',
	'Amount' : 'Cantidad',
	'Current cycle' : 'Ciclo actual',
	'Behaviour rabbits' : 'Comportamiento de las presas - Campo vacío',
	'Behaviour wolves' : 'Comportamiento de los depredadores - Campo vacío',
	'Behaviour rabbits - Malicious code' : 'Comportamiento de las presas - Código malicioso... ¬¬',
	'Behaviour wolves - Malicious code' : 'Comportamiento de los depredadores - Código malicioso... ¬¬',
	'Type' : 'Tipo',
	'File' : 'Fichero',
	'Line' : 'Línea',
	'Message' : 'Mensaje',
	'Total period - Empty field' : 'Duración total - Campo vacío',
	'Daylight period - Empty field' : 'Duración del día - Campo vacío',
	'Night period - Empty field' : 'Duración de la noche - Campo vacío',
	'Size (height) of the world - Empty field' : 'Dimensión (largo) del mundo - Campo vacío',
	'Size (width) of the world - Empty field' : 'Dimensión (ancho) del mundo - Campo vacío',
	'Change weather each (cycles) - Empty field' : 'Cambiar tiempo cada (ciclos) - Campo vacío',
	'Amount of carrots - Empty field' : 'Cantidad de comida para presas - Campo vacío',
	'Amount of trees - Empty field' : 'Cantidad de elementos estáticos - Campo vacío',
	'Amount of lair - Empty field' : 'Cantidad de elementos de ocultación - Campo vacío',
	'Amount of rabbits - Empty field' : 'Cantidad de presas - Campo vacío',
	'Amount of wolves - Empty field' : 'Cantidad de depredadores - Campo vacío',
	'Begining amount of elements - Empty field' : 'Cantidad inicial de elementos - Campo vacío',
	'Regeneration of carrots each - Empty field' : 'Regeneración de comida para presas cada - Campo vacío',
	'Regeneration of carrots (amount) - Empty field' : 'Regenara comida para presas (cantidad) - Campo vacío',
	'Cycles without eat (rabbits) - Empty field' : 'Ciclos sin comer (presas) - Campo vacío',
	'Cycles without eat (wolves) - Empty field' : 'Ciclos sin comer (depredadores) - Campo vacío',
	'Cycles without sleep (rabbits) - Empty field' : 'Ciclos sin dormir (presas) - Campo vacío',
	'Cycles without sleep (wolves) - Empty field' : 'Ciclos sin dormir (depredadores) - Campo vacío',
	'Rabbits - Limit each (cycles) - Empty field' : 'Presas - Límite cada (ciclos) - Campo vacío',
	'Rabbits - Maximum amount - Empty field' : 'Presas - Cantidad máxima - Campo vacío',
	'Wolves - Limit each (cycles) - Empty field' : 'Depredadores - Límite cada (ciclos) - Campo vacío',
	'Wolves - Maximum amount - Empty field' : 'Depredadores - Cantidad máxima - Campo vacío',
	'Wolves - Need (cycles) - Empty field' : 'Depredadores - Necesitan (ciclos) - Campo vacío',
	'Rabbits - Are sated for (cycles) - Empty field' : 'Presas - Están saciados durante (ciclos) - Campo vacío',
	'Wolves - Are sated for (cycles) - Empty field' : 'Depredadores - Están saciados durante (ciclos) - Campo vacío',
	'Rabbits - Need (cycles) - Empty field' : 'Presas - Necesitan (ciclos) - Campo vacío',
	'Points per actions - Rabbits - Empty field' : 'Puntos por acciones - Presas - Campo vacío',
	'Points per actions - Wolves - Empty field' : 'Puntos por acciones - Depredadores - Campo vacío',
	'Use per action - Smell - Rabbits - Empty field' : 'Consumo por acción - Olfatear - Presas - Campo vacío',
	'Use per action - Smell - Wolves - Empty field' : 'Consumo por acción - Olfatear - Depredadores - Campo vacío',
	'Use per action - Hear - Rabbits - Empty field' : 'Consumo por acción - Oir - Presas - Campo vacío',
	'Use per action - Hear - Wolves - Empty field' : 'Consumo por acción - Oir - Depredadores - Campo vacío',
	'Use per action - See - Rabbits - Empty field' : 'Consumo por acción - Ver - Depredadores - Campo vacío',
	'Use per action - See - Wolves - Empty field' : 'Consumo por acción - Ver - Depredadores - Campo vacío',
	'Use per action - Move - Rabbits - Empty field' : 'Consumo por acción - Mover - Depredadores - Campo vacío',
	'Use per action - Move - Wolves - Empty field' : 'Consumo por acción - Mover - Depredadores - Campo vacío',
	'Use per action - Sleep - Rabbits - Empty field' : 'Consumo por acción - Dormir - Depredadores - Campo vacío',
	'Use per action - Sleep - Wolves - Empty field' : 'Consumo por acción - Dormir - Depredadores - Campo vacío',
	'Use per action - Breed - Rabbits - Empty field' : 'Consumo por acción - Reproducirse - Depredadores - Campo vacío',
	'Use per action - Breed - Wolves - Empty field' : 'Consumo por acción - Reproducirse - Depredadores - Campo vacío',
	'Range per action - See - Rabbits - Empty field' : 'Rango por acción - Ver - Presas - Campo vacío',
	'Range per action - See - Wolves - Empty field' : 'Rango por acción - Ver - Depredadores - Campo vacío',
	'Range per action - Smell - Rabbits - Empty field' : 'Rango por acción - Olfatear - Presas - Campo vacío',
	'Range per action - Smell - Wolves - Empty field' : 'Rango por acción - Olfatear - Depredadores - Campo vacío',
	'Range per action - See - Rabbits - Empty field' : 'Rango por acción - Ver - Presas - Campo vacío',
	'Range per action - See - Wolves - Empty field' : 'Rango por acción - Ver - Depredadores - Campo vacío',
	'Until (cycles) after eating - Rabbits - Empty field' : 'Hasta (ciclos) después de comer - Presas - Campo vacío',
	'Until (cycles) after eating - Wolves - Empty field' : 'Hasta (ciclos) después de comer - Depredadores - Campo vacío',
	'Until (cycles) after sleeping - Rabbits - Empty field' : 'Hasta (ciclos) después de dormir - Presas - Campo vacío',
	'Until (cycles) after sleeping - Wolves - Empty field' : 'Hasta (ciclos) después de dormir - Depredadores - Campo vacío',
	'Behaviour rabbits - Empty field' : 'Comportamiento de las presas - Campo vacío',
	'Behaviour wolves - Empty field' : 'Comportamiento de los depredadores - Campo vacío',
	'Rabbits - Be not sleepy for (cycles) - Empty field' : 'Presas - Sin sueño durante (ciclos) - Campo vacío',
	'Rabbits - Be not sleepy for (cycles) - Wrong format' : 'Presas - Sin sueño durante (ciclos) - Formato incorrecto',
	'Rabbits - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Presas - Sin sueño durante (ciclos) - El número de ciclos tiene que ser menor que el tiempo que pueden pasar sin dormir',
	'Wolves - Be not sleepy for (cycles) - Empty field' : 'Depredadores - Sin sueño durante (ciclos) - Campo vacío',
	'Wolves - Be not sleepy for (cycles) - Wrong format' : 'Depredadores - Sin sueño durante (ciclos) - Formato incorrecto',
	'Wolves - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Depredadores - Sin sueño durante (ciclos) - El número de ciclos tiene que ser menor que el tiempo que pueden pasar sin dormir',
	'Lifetime of carrots - Empty field' : 'Tiempo de vida de la comida para presas - Campo vacío',
	'Lifetime of carrots - Wrong format' : 'Tiempo de vida de la comida para presas - Formato incorrecto',
	'Execution cycle' : 'Ciclo de ejecución'
};

/**
 * Galician dictionary
 */
var ga = {
	'World' : 'Mundo',
	'Elements' : 'Elementos',
	'Restrictions' : 'Restriccións',
	'Period' : 'Ciclos',
	'Actions' : 'Accións',
	'Ranges' : 'Rangos',
	'Behaviour' : 'Comportamento',
	'Total period - Wrong format' : 'Duración total - Formato incorrecto',
	'Total period - It must be equal or more than 2' : 'Duración total - Ten que ser igual ou maior que 2',
	'Daylight period - Wrong format' : 'Duración do día - Formato incorrecto',
	'Daylight period - It must be equal or more than 1' : 'Duración do día - Ten que ser igual ou maior que 1',
	'Night period - Wrong format' : 'Duración da noite - Formato incorrecto',
	'Night period - It must be equal or more than 1' : 'Duración da noite - Ten que ser igual ou maior que 1',
	'Size (height) of the world - Wrong format' : 'Dimensión (largo) do mundo - Formato incorrecto',
	'Size (height) of the world - It must be equal or more than 1' : 'Dimensión (largo) do mundo - Ten que ser igual ou maior que 1',
	'Size (width) of the world - Wrong format' : 'Dimensión (ancho) do mundo - Formato incorrecto',
	'Size (width) of the world - It must be equal or more than 1' : 'Dimensión (ancho) do mundo - Ten que ser igual ou maior que 1',
	'Change weather each (cycles) - Wrong format' : 'Cambiar tempo cada (ciclos) - Formato incorrecto',
	'Change weather each (cycles) - It must be equal or less than total period' : 'Cambiar tempo cada (ciclos) - Ten que ser igual ou menor que o número de ciclos de execución',
	'Amount of carrots - Wrong format' : 'Cantidade de comida para presas - Formato incorrecto',
	'Amount of trees - Wrong format' : 'Cantidade de elementos estáticos - Formato incorrecto',
	'Amount of lair - Wrong format' : 'Cantidade de elementos de ocultación - Formato incorrecto',
	'Amount of rabbits - Wrong format' : 'Cantidade de presas - Formato incorrecto',
	'Amount of wolves - Wrong format' : 'Cantidade de depredadores - Formato incorrecto',
	'Begining amount of elements - It must be equal or less than size world' : 'Cantidade inicial de elementos - Ten que ser menor ou igual que a dimensión do mundo',
	'Regeneration of carrots each - Wrong format' : 'Rexeneración de comida para presas cada',
	'Regeneration of carrots each - The number of cycles mustn\'t be more than total period' : 'Rexenera comida para presas cada - O número de ciclos non pode ser maior que o número de ciclos de execución',
	'Regeneration of carrots each - The number of cycles must be more than 0' : 'Rexenera comida para presas cada - O número de ciclos ten que ser maior que 0',
	'Regeneration of carrots (amount) - Wrong format' : 'Rexenera comida para presas (cantidade) - Formato incorrecto',
	'Cycles without eat (rabbits) - Wrong format' : 'Ciclos sen comer (presas) - Formato incorrecto',
	'Cycles without eat (wolves) - Wrong format' : 'Ciclos sen comer (depredadores) - Formato incorrecto',
	'Cycles without sleep (rabbits) - Wrong format' : 'Ciclos sen dormir (presas) - Formato incorrecto',
	'Cycles without sleep (wolves) - Wrong format' : 'Ciclos sen dormir (depredadores) - Formato incorrecto',
	'Rabbits - Limit each (cycles) - Wrong format' : 'Presas - Límite cada (ciclos) - Formato incorrecto',
	'Rabbits - Maximum amount - Wrong format' : 'Presas - Cantidade máxima - Formato incorrecto',
	'Wolves - Limit each (cycles) - Wrong format' : 'Depredadores - Límite cada (ciclos) - Formato incorrecto',
	'Wolves - Maximum amount - Wrong format' : 'Depredadores - Cantidade máxima - Formato incorrecto',
	'Rabbits - Need (cycles) - Wrong format' : 'Presas - Necesitan (ciclos) - Formato incorrecto',
	'Rabbits - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Presas - Necesitan (ciclos) - Non se pode tardar más da duración do día en comer',
	'Wolves - Need (cycles) - Wrong format' : 'Depredadores - Necesitan (ciclos) - Formato incorrecto',
	'Wolves - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Depredadores - Necesitan (ciclos) - Non se pode tardar más da duración do día en comer',
	'Rabbits - Are sated for (cycles) - Wrong format' : 'Presas - Están saciadas durante (ciclos) - Formato incorrecto',
	'Rabbits - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Presas - Están saciadas durante (ciclos) - O número de ciclos ten que ser menor que o tempo que poden pasar sen comer',
	'Wolves - Are sated for (cycles) - Wrong format' : 'Depredadores - Están saciados durante (ciclos) - Formato incorrecto',
	'Wolves - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Depredadores - Están saciados durante (ciclos) - O número de ciclos ten que ser menor que o tempo que poden pasar sen comer',
	'Rabbits - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Presas - Necesitan (ciclos) - Duración incorrecta, non pode ser maior que o +25% da duración da noite',
	'Wolves - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Depredadores - Necesitan (ciclos) - Duración incorrecta, no pode ser maior que o +25% da duración da noite',
	'Points per actions - Rabbits - Wrong format' : 'Puntos por accións - Presas - Formato incorrecto',
	'Points per actions - Wolves - Wrong format' : 'Puntos por accións - Depredadores - Formato incorrecto',
	'Use per action - Smell - Rabbits - Wrong format' : 'Consumo por acción - Olfatear - Presas - Formato incorrecto',
	'Use per action - Smell - Wolves - Wrong format' : 'Consumo por acción - Olfatear - Depredadores - Formato incorrecto',
	'Use per action - Hear - Rabbits - Wrong format' : 'Consumo por acción - Oir - Presas - Formato incorrecto',
	'Use per action - Hear - Wolves - Wrong format' : 'Consumo por acción - Oir - Depredadores - Formato incorrecto',
	'Use per action - See - Rabbits - Wrong format' : 'Consumo por acción - Ver - Depredadores - Formato incorrecto',
	'Use per action - See - Wolves - Wrong format' : 'Consumo por acción - Ver - Depredadores - Formato incorrecto',
	'Use per action - Move - Rabbits - Wrong format' : 'Consumo por acción - Mover - Depredadores - Formato incorrecto',
	'Use per action - Move - Wolves - Wrong format' : 'Consumo por acción - Mover - Depredadores - Formato incorrecto',
	'Use per action - Sleep - Rabbits - Wrong format' : 'Consumo por acción - Dormir - Depredadores - Formato incorrecto',
	'Use per action - Sleep - Wolves - Wrong format' : 'Consumo por acción - Dormir - Depredadores - Formato incorrecto',
	'Use per action - Breed - Rabbits - Wrong format' : 'Consumo por acción - Reproducirse - Depredadores - Formato incorrecto',
	'Use per action - Breed - Wolves - Wrong format' : 'Consumo por acción - Reproducirse - Depredadores - Formato incorrecto',
	'Range per action - See - Rabbits - Wrong format' : 'Rango por acción - Ver - Presas - Formato incorrecto',
	'Range per action - See - Wolves - Wrong format' : 'Rango por acción - Ver - Depredadores - Formato incorrecto',
	'Range per action - Smell - Rabbits - Wrong format' : 'Rango por acción - Olfatear - Presas - Formato incorrecto',
	'Range per action - Smell - Wolves - Wrong format' : 'Rango por acción - Olfatear - Depredadores - Formato incorrecto',
	'Range per action - See - Rabbits - Wrong format' : 'Rango por acción - Ver - Presas - Formato incorrecto',
	'Range per action - See - Wolves - Wrong format' : 'Rango por acción - Ver - Depredadores - Formato incorrecto',
	'Until (cycles) after eating - Rabbits - Wrong format' : 'Ata (ciclos) despois de comer - Presas - Formato incorrecto',
	'Until (cycles) after eating - Wolves - Wrong format' : 'Ata (ciclos) despois de comer - Depredadores - Formato incorrecto',
	'Until (cycles) after sleeping - Rabbits - Wrong format' : 'Ata (ciclos) despois de dormir - Presas - Formato incorrecto',
	'Until (cycles) after sleeping - Wolves - Wrong format' : 'Ata (ciclos) despois de dormir - Depredadores - Formato incorrecto',
	'Weather' : 'Tempo atmosférico',
	'Cycles' : 'Ciclos',
	'Sunny' : 'Soleado',
	'Rainy' : 'Chuvioso',
	'Windy' : 'Con vento',
	'Foggy' : 'Con néboa',
	'Rabbits' : 'Presas',
	'Wolves' : 'Depredadores',
	'Carrots' : 'Cenorias',
	'Amount' : 'Cantidade',
	'Current cycle' : 'Ciclo actual',
	'Behaviour rabbits' : 'Comportamento das presas - Campo baleiro',
	'Behaviour wolves' : 'Comportamento dos depredadores - Campo baleiro',
	'Behaviour rabbits - Malicious code' : 'Comportamento das presas - Código malicioso... ¬¬',
	'Behaviour wolves - Malicious code' : 'Comportamento dos depredadores - Código malicioso... ¬¬',
	'Type' : 'Tipo',
	'File' : 'Ficheiro',
	'Line' : 'Liña',
	'Message' : 'Mensaxe',
	'Empty field' : 'Campo baleiro',
	'Total period - Empty field' : 'Duración total - Campo baleiro',
	'Daylight period - Empty field' : 'Duración do día - Campo baleiro',
	'Night period - Empty field' : 'Duración da noche - Campo baleiro',
	'Size (height) of the world - Empty field' : 'Dimensión (largo) do mundo - Campo baleiro',
	'Size (width) of the world - Empty field' : 'Dimensión (ancho) do mundo - Campo baleiro',
	'Change weather each (cycles) - Empty field' : 'Cambiar tempo cada (ciclos) - Campo baleiro',
	'Amount of carrots - Empty field' : 'Cantidade de comida para presas - Campo baleiro',
	'Amount of trees - Empty field' : 'Cantidade de elementos estáticos - Campo baleiro',
	'Amount of lair - Empty field' : 'Cantidade de elementos de ocultación - Campo baleiro',
	'Amount of rabbits - Empty field' : 'Cantidade de presas - Campo baleiro',
	'Amount of wolves - Empty field' : 'Cantidade de depredadores - Campo baleiro',
	'Begining amount of elements - Empty field' : 'Cantidade inicial de elementos - Campo baleiro',
	'Regeneration of carrots each - Empty field' : 'Rexeneración de comida para presas cada - Campo baleiro',
	'Regeneration of carrots (amount) - Empty field' : 'Rexenera comida para presas (cantidade) - Campo baleiro',
	'Cycles without eat (rabbits) - Empty field' : 'Ciclos sen comer (presas) - Campo baleiro',
	'Cycles without eat (wolves) - Empty field' : 'Ciclos sen comer (depredadores) - Campo baleiro',
	'Cycles without sleep (rabbits) - Empty field' : 'Ciclos sen dormir (presas) - Campo baleiro',
	'Cycles without sleep (wolves) - Empty field' : 'Ciclos sen dormir (depredadores) - Campo baleiro',
	'Rabbits - Limit each (cycles) - Empty field' : 'Presas - Límite cada (ciclos) - Campo baleiro',
	'Rabbits - Maximum amount - Empty field' : 'Presas - Cantidade máxima - Campo baleiro',
	'Wolves - Limit each (cycles) - Empty field' : 'Depredadores - Límite cada (ciclos) - Campo baleiro',
	'Wolves - Maximum amount - Empty field' : 'Depredadores - Cantidade máxima - Campo baleiro',
	'Rabbits - Need (cycles) - Empty field' : 'Presas - Necesitan (ciclos) - Campo baleiro',
	'Wolves - Need (cycles) - Empty field' : 'Depredadores - Necesitan (ciclos) - Campo baleiro',
	'Points per actions - Rabbits - Empty field' : 'Puntos por accións - Presas - Campo baleiro',
	'Points per actions - Wolves - Empty field' : 'Puntos por accións - Depredadores - Campo baleiro',
	'Rabbits - Are sated for (cycles) - Empty field' : 'Presas - Están saciadas durante (ciclos) - Campo baleiro',
	'Wolves - Are sated for (cycles) - Empty field' : 'Depredadores - Están saciados durante (ciclos) - Campo baleiro',
	'Use per action - Smell - Rabbits - Empty field' : 'Consumo por acción - Olfatear - Presas - Campo baleiro',
	'Use per action - Smell - Wolves - Empty field' : 'Consumo por acción - Olfatear - Depredadores - Campo baleiro',
	'Use per action - Hear - Rabbits - Empty field' : 'Consumo por acción - Oir - Presas - Campo baleiro',
	'Use per action - Hear - Wolves - Empty field' : 'Consumo por acción - Oir - Depredadores - Campo baleiro',
	'Use per action - See - Rabbits - Empty field' : 'Consumo por acción - Ver - Depredadores - Campo baleiro',
	'Use per action - See - Wolves - Empty field' : 'Consumo por acción - Ver - Depredadores - Campo baleiro',
	'Use per action - Move - Rabbits - Empty field' : 'Consumo por acción - Mover - Depredadores - Campo baleiro',
	'Use per action - Move - Wolves - Empty field' : 'Consumo por acción - Mover - Depredadores - Campo baleiro',
	'Use per action - Sleep - Rabbits - Empty field' : 'Consumo por acción - Durmir - Depredadores - Campo baleiro',
	'Use per action - Sleep - Wolves - Empty field' : 'Consumo por acción - Durmir - Depredadores - Campo baleiro',
	'Use per action - Breed - Rabbits - Empty field' : 'Consumo por acción - Reproducirse - Depredadores - Campo baleiro',
	'Use per action - Breed - Wolves - Empty field' : 'Consumo por acción - Reproducirse - Depredadores - Campo baleiro',
	'Range per action - See - Rabbits - Empty field' : 'Rango por acción - Ver - Presas - Campo baleiro',
	'Range per action - See - Wolves - Empty field' : 'Rango por acción - Ver - Depredadores - Campo baleiro',
	'Range per action - Smell - Rabbits - Empty field' : 'Rango por acción - Olfatear - Presas - Campo baleiro',
	'Range per action - Smell - Wolves - Empty field' : 'Rango por acción - Olfatear - Depredadores - Campo baleiro',
	'Range per action - See - Rabbits - Empty field' : 'Rango por acción - Ver - Presas - Campo baleiro',
	'Range per action - See - Wolves - Empty field' : 'Rango por acción - Ver - Depredadores - Campo baleiro',
	'Until (cycles) after eating - Rabbits - Empty field' : 'Ata (ciclos) despois de comer - Presas - Campo baleiro',
	'Until (cycles) after eating - Wolves - Empty field' : 'Ata (ciclos) despois de comer - Depredadores - Campo baleiro',
	'Until (cycles) after sleeping - Rabbits - Empty field' : 'Ata (ciclos) despois de dormir - Presas - Campo baleiro',
	'Until (cycles) after sleeping - Wolves - Empty field' : 'Ata (ciclos) despois de dormir - Depredadores - Campo baleiro',
	'Behaviour rabbits - Empty field' : 'Comportamento das presas - Campo baleiro',
	'Behaviour wolves - Empty field' : 'Comportamento dos depredadores - Campo baleiro',
	'Rabbits - Be not sleepy for (cycles) - Empty field' : 'Presas - Sen sono durante (ciclos) - Campo baleiro',
	'Rabbits - Be not sleepy for (cycles) - Wrong format' : 'Presas - Sen sono durante (ciclos) - Formato incorrecto',
	'Rabbits - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Presas - Sen sono durante (ciclos) - O número de ciclos ten que ser menor que o tempo que poden pasar sen durmir',
	'Wolves - Be not sleepy for (cycles) - Empty field' : 'Depredadores - Sen sono durante (ciclos) - Campo baleiro',
	'Wolves - Be not sleepy for (cycles) - Wrong format' : 'Depredadores - Sen sono durante (ciclos) - Formato incorrecto',
	'Wolves - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Depredadores - Sen sono durante (ciclos) - O número de ciclos ten que ser menor que o tempo que poden pasar sen durmir',
	'Lifetime of carrots - Empty field' : 'Tempo de vida da comida para presas - Campo baleiro',
	'Lifetime of carrots - Wrong format' : 'Tempo de vida da comida para presas - Formato incorrecto',
	'Execution cycle' : 'Ciclo de execución'
};

/**
 * English dictionary
 */
var en = {
	'World' : 'World',
	'Elements' : 'Elements',
	'Restrictions' : 'Restrictions',
	'Period' : 'Period',
	'Actions' : 'Actions',
	'Ranges' : 'Ranges',
	'Behaviour' : 'Behaviour',
	'Total period - Wrong format' : 'Total period - Wrong format',
	'Total period - It must be equal or more than 2' : 'Total period - It must be equal or more than 2',
	'Daylight period - Wrong format' : 'Daylight period - Wrong format',
	'Daylight period - It must be equal or more than 1' : 'Daylight period - It must be equal or more than 1',
	'Night period - Wrong format' : 'Night period - Wrong format',
	'Night period - It must be equal or more than 1' : 'Night period - It must be equal or more than 1',
	'Size (height) of the world - Wrong format' : 'Size (height) of the world - Wrong format',
	'Size (height) of the world - It must be equal or more than 1' : 'Size (height) of the world - It must be equal or more than 1',
	'Size (width) of the world - Wrong format' : 'Size (width) of the world - Wrong format',
	'Size (width) of the world - It must be equal or more than 1' : 'Size (width) of the world - It must be equal or more than 1',
	'Change weather each (cycles) - Wrong format' : 'Change weather each (cycles) - Wrong format',
	'Change weather each (cycles) - It must be equal or less than total period' : 'Change weather each (cycles) - It must be equal or less than total period',
	'Amount of carrots - Wrong format' : 'Amount of food for preys - Wrong format',
	'Amount of trees - Wrong format' : 'Amount of static elements - Wrong format',
	'Amount of lair - Wrong format' : 'Amount of masking elements - Wrong format',
	'Amount of rabbits - Wrong format' : 'Amount of preys - Wrong format',
	'Amount of wolves - Wrong format' : 'Amount of predators - Wrong format',
	'Begining amount of elements - It must be equal or less than size world' : 'Begining amount of elements - It must be equal or less than size world',
	'Regeneration of carrots each - Wrong format' : 'Regeneration of food for preys each - Wrong format',
	'Regeneration of carrots each - The number of cycles mustn\'t be more than total period' : 'Regeneration of food for preys each - The number of cycles mustn\'t be more than total period',
	'Regeneration of carrots each - The number of cycles must be more than 0' : 'Regeneration of food for preys each - The number of cycles must be more than 0',
	'Regeneration of carrots (amount) - Wrong format' : 'Regeneration of food for preys (amount) - Wrong format',
	'Cycles without eat (rabbits) - Wrong format' : 'Cycles without eat (preys) - Wrong format',
	'Cycles without eat (wolves) - Wrong format' : 'Cycles without eat (predators) - Wrong format',
	'Cycles without sleep (rabbits) - Wrong format' : 'Cycles without sleep (preys) - Wrong format',
	'Cycles without sleep (wolves) - Wrong format' : 'Cycles without sleep (predators) - Wrong format',
	'Rabbits - Limit each (cycles) - Wrong format' : 'Preys - Limit each (cycles) - Wrong format',
	'Rabbits - Maximum amount - Wrong format' : 'Preys - Maximum amount - Wrong format',
	'Wolves - Limit each (cycles) - Wrong format' : 'Predators - Limit each (cycles) - Wrong format',
	'Wolves - Maximum amount - Wrong format' : 'Predators - Maximum amount - Wrong format',
	'Rabbits - Need (cycles) - Wrong format' : 'Preys - Need (cycles) - Wrong format',
	'Rabbits - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Preys - Need (cycles) - Can\'t need more than daylight duration to eat',
	'Wolves - Need (cycles) - Wrong format' : 'Predators - Need (cycles) - Wrong format',
	'Wolves - Need (cycles) - Can\'t need more than daylight duration to eat' : 'Predators - Need (cycles) - Can\'t need more than daylight duration to eat',
	'Rabbits - Are sated for (cycles) - Wrong format' : 'Preys - Are sated for (cycles) - Wrong format',
	'Rabbits - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Preys - Are sated for (cycles) - The number of cycles must be less than the time without eat',
	'Wolves - Are sated for (cycles) - Wrong format' : 'Predators - Are sated for (cycles) - Wrong format',
	'Wolves - Are sated for (cycles) - The number of cycles must be less than the time without eat' : 'Predators - Are sated for (cycles) - The number of cycles must be less than the time without eat',
	'Rabbits - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Preys - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period',
	'Wolves - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period' : 'Predators - Need (cycles) - Wrong period, it mustn\'t be more than 25% of night period',
	'Points per actions - Rabbits - Wrong format' : 'Points per actions - Preys - Wrong format',
	'Points per actions - Wolves - Wrong format' : 'Points per actions - Predators - Wrong format',
	'Use per action - Smell - Rabbits - Wrong format' : 'Use per action - Smell - Preys - Wrong format',
	'Use per action - Smell - Wolves - Wrong format' : 'Use per action - Smell - Predators - Wrong format',
	'Use per action - Hear - Rabbits - Wrong format' : 'Use per action - Hear - Preys - Wrong format',
	'Use per action - Hear - Wolves - Wrong format' : 'Use per action - Hear - Predators - Wrong format',
	'Use per action - See - Rabbits - Wrong format' : 'Use per action - See - Preys - Wrong format',
	'Use per action - See - Wolves - Wrong format' : 'Use per action - See - Predators - Wrong format',
	'Use per action - Move - Rabbits - Wrong format' : 'Use per action - Move - Preys - Wrong format',
	'Use per action - Move - Wolves - Wrong format' : 'Use per action - Move - Predators - Wrong format',
	'Use per action - Sleep - Rabbits - Wrong format' : 'Use per action - Sleep - Preys - Wrong format',
	'Use per action - Sleep - Wolves - Wrong format' : 'Use per action - Sleep - Predators - Wrong format',
	'Use per action - Breed - Rabbits - Wrong format' : 'se per action - Breed - Preys - Wrong format',
	'Use per action - Breed - Wolves - Wrong format' : 'Use per action - Breed - Predators - Wrong format',
	'Range per action - See - Rabbits - Wrong format' : 'Range per action - See - Preys - Wrong format',
	'Range per action - See - Wolves - Wrong format' : 'Range per action - See - Predators - Wrong format',
	'Range per action - Smell - Rabbits - Wrong format' : 'Range per action - Smell - Preys - Wrong format',
	'Range per action - Smell - Wolves - Wrong format' : 'Range per action - Smell - Predators - Wrong format',
	'Range per action - See - Rabbits - Wrong format' : 'Range per action - See - Preys - Wrong format',
	'Range per action - See - Wolves - Wrong format' : 'Range per action - See - Predators - Wrong format',
	'Until (cycles) after eating - Rabbits - Wrong format' : 'Until (cycles) after eating - Preys - Wrong format',
	'Until (cycles) after eating - Wolves - Wrong format' : 'Until (cycles) after eating - Predators - Wrong format',
	'Until (cycles) after sleeping - Rabbits - Wrong format' : 'Until (cycles) after sleeping - Preys - Wrong format',
	'Until (cycles) after sleeping - Wolves - Wrong format' : 'Until (cycles) after sleeping - Predators - Wrong format',
	'Weather' : 'Tiempo atmosférico',
	'Cycles' : 'Cycles',
	'Sunny' : 'Sunny',
	'Rainy' : 'Rainy',
	'Windy' : 'Windy',
	'Foggy' : 'Foggy',
	'Rabbits' : 'Preys',
	'Wolves' : 'Predators',
	'Carrots' : 'Food for preys',
	'Amount' : 'Amount',
	'Current cycle' : 'Current cycle',
	'Behaviour rabbits' : 'Behaviour preys - Empty field',
	'Behaviour wolves' : 'Behaviour predators - Empty field',
	'Behaviour rabbits - Malicious code' : 'Behaviour preys - Malicious code... ¬¬',
	'Behaviour wolves - Malicious code' : 'Behaviour predators - Malicious code... ¬¬',
	'Type' : 'Type',
	'File' : 'File',
	'Line' : 'Line',
	'Message' : 'Message',
	'Empty field' : 'Empty field',
	'Total period - Empty field' : 'Total period - Empty field',
	'Daylight period - Empty field' : 'Daylight period - Empty field',
	'Night period - Empty field' : 'Night period - Empty field',
	'Size (height) of the world - Empty field' : 'Size (height) of the world - Empty field',
	'Size (width) of the world - Empty field' : 'Size (width) of the world - Empty field',
	'Change weather each (cycles) - Empty field' : 'Change weather each (cycles) - Empty field',
	'Amount of carrots - Empty field' : 'Amount of food for preys - Empty field',
	'Amount of trees - Empty field' : 'Amount of static elements - Empty field',
	'Amount of lair - Empty field' : 'Amount of masking elements - Empty field',
	'Amount of rabbits - Empty field' : 'Amount of preys - Empty field',
	'Amount of wolves - Empty field' : 'Amount of predators - Empty field',
	'Begining amount of elements - Empty field' : 'Begining amount of elements - Empty field',
	'Regeneration of carrots each - Empty field' : 'Regeneration of food for preys each - Empty field',
	'Regeneration of carrots (amount) - Empty field' : 'Regeneration of food for preys (amount) - Empty field',
	'Cycles without eat (rabbits) - Empty field' : 'Cycles without eat (preys) - Empty field',
	'Cycles without eat (wolves) - Empty field' : 'Cycles without eat (predators) - Empty field',
	'Cycles without sleep (rabbits) - Empty field' : 'Cycles without sleep (preys) - Empty field',
	'Cycles without sleep (wolves) - Empty field' : 'Cycles without sleep (predators) - Empty field',
	'Rabbits - Limit each (cycles) - Empty field' : 'Preys - Limit each (cycles) - Empty field',
	'Rabbits - Maximum amount - Empty field' : 'Preys - Maximum amount - Empty field',
	'Wolves - Limit each (cycles) - Empty field' : 'Predators - Limit each (cycles) - Empty field',
	'Wolves - Maximum amount - Empty field' : 'Predators - Maximum amount - Empty field',
	'Rabbits - Need (cycles) - Empty field' : 'Preys - Need (cycles) - Empty field',
	'Wolves - Need (cycles) - Empty field' : 'Predators - Need (cycles) - Empty field',
	'Points per actions - Rabbits - Empty field' : 'Points per actions - Preys - Empty field',
	'Points per actions - Wolves - Empty field' : 'Points per actions - Predators - Empty field',
	'Rabbits - Are sated for (cycles) - Empty field' : 'Preys - Are sated for (cycles) - Empty field',
	'Wolves - Are sated for (cycles) - Empty field' : 'Predators - Are sated for (cycles) - Empty field',
	'Use per action - Smell - Rabbits - Empty field' : 'Use per action - Smell - Preys - Empty field',
	'Use per action - Smell - Wolves - Empty field' : 'Use per action - Smell - Predators - Empty field',
	'Use per action - Hear - Rabbits - Empty field' : 'Use per action - Hear - Preys - Empty field',
	'Use per action - Hear - Wolves - Empty field' : 'Use per action - Hear - Predators - Empty field',
	'Use per action - See - Rabbits - Empty field' : 'Use per action - See - Preys - Empty field',
	'Use per action - See - Wolves - Empty field' : 'Use per action - See - Predators - Empty field',
	'Use per action - Move - Rabbits - Empty field' : 'Use per action - Move - Preys - Empty field',
	'Use per action - Move - Wolves - Empty field' : 'Use per action - Move - Predators - Empty field',
	'Use per action - Sleep - Rabbits - Empty field' : 'Use per action - Sleep - Preys - Empty field',
	'Use per action - Sleep - Wolves - Empty field' : 'Use per action - Sleep - Predators - Empty field',
	'Use per action - Breed - Rabbits - Empty field' : 'Use per action - Breed - Preys - Empty field',
	'Use per action - Breed - Wolves - Empty field' : 'Use per action - Breed - Predators - Empty field',
	'Range per action - See - Rabbits - Empty field' : 'Range per action - See - Preys - Empty field',
	'Range per action - See - Wolves - Empty field' : 'Range per action - See - Predators - Empty field',
	'Range per action - Smell - Rabbits - Empty field' : 'Range per action - Smell - Preys - Empty field',
	'Range per action - Smell - Wolves - Empty field' : 'Range per action - Smell - Predators - Empty field',
	'Range per action - See - Rabbits - Empty field' : 'Range per action - See - Preys - Empty field',
	'Range per action - See - Wolves - Empty field' : 'Range per action - See - Predators - Empty field',
	'Until (cycles) after eating - Rabbits - Empty field' : 'Until (cycles) after eating - Preys - Empty field',
	'Until (cycles) after eating - Wolves - Empty field' : 'Until (cycles) after eating - Predators - Empty field',
	'Until (cycles) after sleeping - Rabbits - Empty field' : 'Until (cycles) after sleeping - Preys - Empty field',
	'Until (cycles) after sleeping - Wolves - Empty fiepreysld' : 'Until (cycles) after sleeping - Predators - Empty field',
	'Behaviour rabbits - Empty field' : 'Behaviour preys - Empty field',
	'Behaviour wolves - Empty field' : 'Behaviour predators - Empty field',
	'Rabbits - Be not sleepy for (cycles) - Empty field' : 'Preys - Be not sleepy for (cycles) - Empty field',
	'Rabbits - Be not sleepy for (cycles) - Wrong format' : 'Preys - Be not sleepy for (cycles) - Wrong format',
	'Rabbits - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Preys - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep',
	'Wolves - Be not sleepy for (cycles) - Empty field' : 'Predators - Be not sleepy for (cycles) - Empty field',
	'Wolves - Be not sleepy for (cycles) - Wrong format' : 'Predators - Be not sleepy for (cycles) - Wrong format',
	'Wolves - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep' : 'Predators - Be not sleepy for (cycles) - The number of cycles must be less than the time without sleep',
	'Lifetime of carrots - Empty field' : 'Lifetime of food for preys - Empty field',
	'Lifetime of carrots - Wrong format' : 'Lifetime of food for preys - Wrong format',
	'Execution cycle' : 'Execution cycle'
};